### ISSUE TITLE
using cl4cds with custom classloaders

### ISSUE THREAD

**Issue by ashu-mehra** [simonis/cl4cds#5]
From the Readme it appears `cl4cds` should help to add classes loaded by custom loaders to the shared archive. I tried to use `cl4cds` with my sample custom loader.

My test program consists of 3 classes:
1. `MyClassLoader.java` - custom loader that loads classes from `classRepo/sample.jar`
```
import java.util.jar.JarFile;
import java.util.zip.ZipEntry;
import java.io.InputStream;

class MyClassLoader extends ClassLoader {
        private static final String CLASS_REPO = System.getProperty("user.dir") + "/classRepo/sample.jar";

        public MyClassLoader() {
        }

        protected Class<?> findClass(String name) {
                byte[] classBytes = loadClassData(name);
                return defineClass(name, classBytes, 0, classBytes.length);
        }
        private byte[] loadClassData(String name) {
                System.out.println("Loading class from disk");
                try {
                        JarFile jf = new JarFile(CLASS_REPO);
                        ZipEntry entry = jf.getEntry(name + ".class");
                        InputStream is = jf.getInputStream(entry);
                        byte b[] = new byte[(int)entry.getSize()];
                        int read = is.read(b);
                        if (read != b.length) {
                                System.out.println("Requested " + b.length + " bytes, read " + read + " bytes");
                        }
                        return b;
                } catch(Exception e) {
                        e.printStackTrace();
                }
                return null;
        }
}
```
2. `TestLoader.java` - main program
```
import java.io.File;
import java.net.URL;
import java.net.URLClassLoader;
import java.lang.reflect.Method;

public class TestLoader {
	public static void main(String args[]) throws Exception {
		MyClassLoader loader = new MyClassLoader();
		Class sample = loader.loadClass("Sample");
		if (sample != null) {
			Method foo = sample.getMethod("foo");
			if (foo != null) {
				foo.invoke(null);
			}
		}
	}
}
```
3. `Sample.java` - This class is present in `classRepo/sample.jar`
```
public class Sample {
	public static void foo() {
		System.out.println("In Sample.foo()");
	}
}
```

`TestLoader` creates an instance of `MyClassLoader` and asks it to load `Sample` class. `MyClassLoader` loads the requested class from `classRepo/sample.jar`.

I tried using `cl4cds` as below:
```
$ $JAVA_HOME/bin/java -version
openjdk version "10" 2018-03-20
OpenJDK Runtime Environment 18.3 (build 10+46)
OpenJDK 64-Bit Server VM 18.3 (build 10+46, mixed mode)

$ $JAVA_HOME/bin/java -Xlog:class+load=debug:file=classtrace TestLoader
Loading class from disk
In Sample.foo()

$ $JAVA_HOME/bin/java -cp cl4cds/src/classes io.simonis.cl4cds classtrace classlist
Skipping Sample from __JVM_DefineClass__ - reason: dynamically generated class
```

Couple of points:
1) I am not sure why the Sample is being considered as dynamically generated class.
2) Secondly, as per the output `classlist` does not contain `Sample`. That means shared archive generated using `classlist` won't have `Sample` in it.

Unless I am missing something, it looks like `cl4cds` is not yet handling this particular pattern of custom classloaders. Is there any plan to handle such scenarios?
What kind of custom classloaders can benefit from `cl4cds`?

Thanks!

**Comment by simonis** [comment]
Hi Ashu-Mehra,

thanks for trying cl4cds!

In order to answer your question you'll first have to understand how CDS works in Hotspot.

One of the fundamental problems of CDS in HotSpot is the fact that class dumping is a static, off-line step. This means that the CDS archive is not created while you run your application. Instead, it is created in an extra step, when you invoke java with "Xshare:dump". But when the archive is dumped, the VM doesn't actually executes your program. Instead it just loads all the classes from the SharedClassListFile and dumps them into the SharedArchiveFile. It is important to know that all the classes are loaded by the boot class loader during the dump step!

For class which are located on the class path that's obviously no problem, but for application classes which are loaded by custom user class loaders at runtime, the boot class loader can not find their location. That's why we need the extended class list syntax which is generated by 'cl4cds' and contains an additional "source" attribute for such kind of classes.

'cl4cds' on the other hand uses the output of "Xlog:class+load=debug" which already outputs the location of loaded classes to generate this extra "source" attribute. But "Xlog" can only print the location if it was handed over to the VM when calling "ClassLoader::defineClass()". You may have realized that there are several overloaded versions of "defineClass()", the simple one which you are calling from "MyClassLoader" but also to other variants which take an additional "ProtectionDomain" argument. ProtectionDomain is actually a structure which contains a "CodeSource" and a "PermissionCollection". As the name implies, the CodeSource part of the protection domain actually contains the source information of a class which is recorded in the VM and finally printed by "Xlog:class+load=debug". 

If a class is defined by a call to the "defineClass()" version without a ProtectionDomain argument, the VM will print "\_\_JVM_DefineClass__" as the location, because it doesn't know better. "\_\_JVM_DefineClass__" is actually the name of the HotSpot internal method which implements the class definition. Because this happens mostly for dynamically generated classes like "VM anonymous classes", proxy classes, reflection classes, etc., "cl4cds" prints the message "reason: dynamically generated class" if it can not find the location of a class. But in fact this only means that it can not find the location of that class. You an easily verify that by running your "TestLoader" example with "-Xlog:class+load". It will output the following line when loading the "Sample" class:
```
[0,176s][info][class,load] Sample source: __JVM_DefineClass__
```
So until now that has been just the explanation why you couldn't share your "Sample" class in the shared class archive. But how can you fix this problem? You definitely have to pass the location of your classes to the VM and you actually have three possibilities to achieve that.

The first one is to call a version of "defineClass()" with a ProtectionDomain argument that contains the source location of the loaded class. That may look as follows in the context of your example:

```java
        protected Class<?> findClass(String name) {
                byte[] classBytes = loadClassData(name);
                URL url = null;
                try {
                    url = new URL("file:" + CLASS_REPO);
                } catch (Exception e) {
                    System.out.println(e);
                }
                CodeSource cs = new CodeSource(url, (Certificate[])null);
                Permissions perm =  new Permissions();
                ProtectionDomain pd = new ProtectionDomain(cs, perm);
                return defineClass(name, classBytes, 0, classBytes.length, pd);
        }
```
The second option would be to derive your class loader from "SecureClassLoader" which provides a version of "defineClass()" which takes an additional "CodeSource" argument. I've sketched that in the following example:
```java
import java.util.jar.JarFile;
import java.util.zip.ZipEntry;
import java.io.InputStream;
import java.net.URL;
import java.security.CodeSource;
import java.security.SecureClassLoader;
import java.security.cert.Certificate;

class MySecureClassLoader extends SecureClassLoader {
        private static final String CLASS_REPO = System.getProperty("user.dir") + "/classRepo/sample.jar";

        protected Class<?> findClass(String name) {
                byte[] classBytes = loadClassData(name);
                URL url = null;
                try {
                    url = new URL("file:" + CLASS_REPO);
                } catch (Exception e) {
                    System.out.println(e);
                }
                CodeSource cs = new CodeSource(url, (Certificate[])null);
                return defineClass(name, classBytes, 0, classBytes.length, cs);
        }
        private byte[] loadClassData(String name) {
                System.out.println("Loading class from disk");
                try {
                        JarFile jf = new JarFile(CLASS_REPO);
                        ZipEntry entry = jf.getEntry(name + ".class");
                        InputStream is = jf.getInputStream(entry);
                        byte b[] = new byte[(int)entry.getSize()];
                        int read = is.read(b);
                        if (read != b.length) {
                                System.out.println("Requested " + b.length + " bytes, read " + read + " bytes");
                        }
                        return b;
                } catch(Exception e) {
                        e.printStackTrace();
                }
                return null;
        }
}
```
Finally, you could simply derive your class loader directly from URLClassLoader which will handle all the before mentioned actions automatically. It could look as simple as:
```java
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;

class MyURLClassLoader extends URLClassLoader {
        private static final String CLASS_REPO = System.getProperty("user.dir") + "/classRepo/sample.jar";

        MyURLClassLoader() throws MalformedURLException {
                super(new URL[] { new URL("file:" + CLASS_REPO) });
        }
}
```
Hope this helps. Please let me know if you have any additional questions/comments.

**Comment by ashu-mehra** [comment]
@simonis your explanation clarifies things a lot. Thanks for taking the effort to put up this explanation and for the updated examples.
